icons_format = " {icon} "

[theme]
theme = "srcery"
[theme.overrides]
separator = " "
# separator_fg = "#FFFFFF"

[icons]
icons = "material-nf"

# [[block]]
# block = "pomodoro"
# format = "$icon{$message|}"
# message = "Break time! (Click to start the break!)"
# break_message = "Back to work!"
# notify_cmd = "notify-send --app-name=pomodoro '{msg}'"

# [[block]]
# block = "custom"
# format = "Clipboard: $text"
# command = "xsel --clipboard | wc -w"
# interval = 10

# [[block]]
# block = "focused_window"
# format = "$title.str(max_w:32)    "
# driver = "auto"

# [[block]]
# block = "custom"
# format = "$text"
# watch_files = ["~/.config/weather"]
# command = "cat ~/.config/weather"
# interval = "once"

[[block]]
block = "weather"
format = "$icon$weather  $temp"
format_alt = "$icon$weather  $temp  $humidity  {$wind}mph"
interval = 1800
autolocate = true
autolocate_interval = 7200
[block.service]
name = "metno"

[[block]]
block = "docker"
format = "$icon$running "
interval = 60

# [[block]]
# block = "pacman"
# interval = 7200
# # signal = 1
# format = "$icon$pacman.eng(w:1) "
# format_up_to_date = ""

# [[block]]
# block = "notify"
# driver = "dunst"
# format = "$icon"

[[block]]
block = "disk_space"
path = "/"
format = "$icon"
format_alt = "$icon$available / $total"
warning = 20.0
alert = 10.0

[[block]]
block = "disk_space"
path = "/home"
format = "󰋜 "
format_alt = "󰋜 $available / $total"
warning = 20.0
alert = 10.0

[[block]]
block = "custom"
# name = "ip address ipv4 ipv6"
format = "󰩟 $text"
cycle = ["", "dig +short myip.opendns.com @resolver1.opendns.com", "dig TXT +short o-o.myaddr.l.google.com @ns1.google.com"]

[[block]]
block = "custom"
# name = "vpn"  # not valid, just for ease of finding
format = "󰖂 $text"
cycle = [
  "",
  "echo $(tailscale switch --list | awk '{ print $3 }' | sed -nr 's/\\*//p')  $(tailscale status --json | jq -r '.MagicDNSSuffix')",
]

[[block]]
block = "net"
format = "$icon"
format_alt = "$icon$ssid $ip"
missing_format = ""

[[block]]
block = "memory"
format = "$icon"
format_alt = "$icon$mem_used / $mem_total ($mem_used_percents)"
warning_mem = 50.0
critical_mem = 90.0
interval = 30

# [[block]]
# block = "nvidia_gpu"

[[block]]
block = "cpu"
format = "$icon"
format_alt = "$icon $utilization $frequency $boost"

[[block]]
block = "temperature"
format = "$icon"
format_alt = "$icon $average avg, $max max"

[[block]]
block = "backlight"
format = "$icon"

[[block]]
block = "sound"
format = "$icon"

[[block]]
block = "time"
interval = 60
[block.format]
full = "$timestamp.datetime(f:'%a %m/%d %R', l:en_US)"
short = "$timestamp.datetime(f:'%a')"

[[block]]
block = "battery"
format = "$icon$percentage" # $power $time
full_format = "$icon"
empty_format = "$icon"
missing_format = ""
interval = 60
